name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:   # manual run ka option bhi aa jayega

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
         flutter-version: '3.22.0' # stable version use karo

      - name: Verify Flutter
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (3 versions)
        run: flutter build apk --release --split-per-abi

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: release-apks
          path: build/app/outputs/flutter-apk/*.apk
